### ISSUE TITLE
bashrc.sls not included

### ISSUE THREAD

**Issue by clementcohen** [saltstack-formulas/users-formula#105]
HI, 
I'm beginner with salt and I try to configure a user here's my pillar: 

```
users:
  ## Full list of pillar values
  clement:
    fullname: Clement COHEN
    password:########
    enforce_password: False
    # WARNING: If 'empty_password' is set to True, the 'password' statement
    # will be ignored by enabling password-less login for the user.
    empty_password: False
    home: /home/clement
    createhome: true
    roomnumber: "A-1"
    workphone: "#####"
    homephone: "#####"
    manage_vimrc: True
    manage_bashrc: True
    manage_profile: True
   ...
```

I try to include it  in init.sls 

```
{% set used_bashrc = [] %}
{%- if 'manage_bashrc' in user %}
{%- do used_bashrc.append(1) %}
{%- endif %}
{%- endfor %}

{%- if used_bashrc %}
include:
  - users.bashrc
{% endif %}
```

but i've an error : 

```
    Data failed to compile:
----------
    Rendering SLS "base:users" failed: Conflicting ID 'include'

```

I also edit the file  in users/files/bashrc/bashrc

if I don't include it, It do nothing (the bashrc file is not copied)

**Comment by ketzacoatl** [comment]
@clementcohen, the `users/init.sls` already has an `include` statement at https://github.com/saltstack-formulas/users-formula/blob/master/users/init.sls#L24, so if you get that error, check that you are not appending that include - you can only have one `include` statement in each `.sls`
