### ISSUE TITLE
An ssh_keys pillar example sure would be useful

### ISSUE THREAD

**Issue by T3KN0KRAT** [saltstack-formulas/users-formula#109]
Maybe it's because I'm just learning here, but it _could_ be helpful to have a examples to check my ssh_keys and ssh_auth pillars against.

**Comment by gravyboat** [comment]
Is the `pillar.example` not comprehensive enough? https://github.com/saltstack-formulas/users-formula/blob/master/pillar.example#L44

**Comment by 0xf10e** [comment]
I know I quote my `ssh_auth` entries so maybe that's the problem here.
If it only works with single quotes around the keys the `pillar.example` should make this clear.

Am 17. April 2016 06:06:56 MESZ, schrieb Forrest <notifications@github.com>:

**Comment by T3KN0KRAT** [comment]
Well, the pillar.example was indeed comprehensive enough, and it describes very well how to add ssh_keys inline.  I suppose what I was looking for was more of how to create, for example, an ssh_keys pillar.  Again, this was more of a "nice to have" rather than a bug or a need.  After all, I did figure out the ssh_keys pillar structure that would work with the user state.  There's no need to keep this open.  Thanks for replying!
