### ISSUE TITLE
prime_group needs gid as a number

### ISSUE THREAD

**Issue by martinadolfi** [saltstack-formulas/users-formula#110]
When you want to set a different prime group to a user, you have to set the group name and gid. If you don´t set the gid it will fail.
It would be great if you can just tell the name of the group and everything goes smooth.

**Comment by martinadolfi** [comment]
Hey, I made this changes and it works properly for me. Maybe you can checkit out and see if it fits here.

```diff
diff --git a/users/init.sls b/users/init.sls
index ca44a40..591bea5 100644
--- a/users/init.sls
+++ b/users/init.sls
@@ -70,9 +70,12 @@ users_{{ name }}_user:
     - name: {{ user_group }}
     {%- if 'prime_group' in user and 'gid' in user['prime_group'] %}
     - gid: {{ user['prime_group']['gid'] }}
+    {%- elif 'prime_group' in user and 'name' in user['prime_group'] %}
+    - name: {{ user['prime_group']['name'] }}
     {%- elif 'uid' in user %}
     - gid: {{ user['uid'] }}
     {%- endif %}
+
   user.present:
     - name: {{ name }}
     - home: {{ home }}
@@ -94,6 +97,8 @@ users_{{ name }}_user:
     {% endif -%}
     {% if 'prime_group' in user and 'gid' in user['prime_group'] -%}
     - gid: {{ user['prime_group']['gid'] }}
+    {% elif 'prime_group' in user and 'name' in user['prime_group'] -%}
+    - gid: {{ user['prime_group']['name'] }}
     {% else -%}
     - gid_from_name: True
     {% endif -%}
```

**Comment by babilen** [comment]
A PR would be helpful here!

**Comment by daks** [comment]
I got the same problem than described. Is this issue stuck waiting for a PR?

**Comment by gravyboat** [comment]
@daks Yes. None of the Salt devs work on the formulas so it's all up to PRs from the community.

**Comment by IMBArator** [comment]
I opened PR #141.
It should fix this issue ;)

**Comment by 0xf10e** [comment]
@martinadolfi has #141 fixed this?

**Comment by martinadolfi** [comment]
Yeap, I tested latest releases and it works just fine.
Regards!
M.

**Comment by IMBArator** [comment]
Yes, #141 fixed this and is already merged :) . I think this Issue can be closed.

**Comment by babilen** [comment]
Thanks for letting us know!
