### ISSUE TITLE
Commit d3e3122624 broken support for non default home dirs

### ISSUE THREAD

**Issue by enver** [saltstack-formulas/users-formula#111]
In last commit https://github.com/saltstack-formulas/users-formula/commit/d3e3122624fc5dbfe42476154fa80a15d13c2876 in file user_files.sls line 10 ``` {%- set home = user.get('home', "/home/%s" % username) -%} ``` user.get always returns null, forcing use of default home /home/<username>. In my case I manage root account with this formula and although I've home set to /root it still tries to use /home/root as a home dir for root user.

Please revert this commit

**Comment by gravyboat** [comment]
Hmm, I feel like these are both annoying edge cases, on one hand I completely understand where you are coming from and think it's a fair complaint. On the other I dislike every user having to use `/home/user`, I'm going to revert this for now, can you try to think of a solution? I will do so as well.

**Comment by gravyboat** [comment]
@enver This is addressed. If you want to propose a patch I would love to see it.

**Comment by enver** [comment]
@gravyboat Seems to be fixed with #114
