### ISSUE TITLE
Resolve `git.config` error where minion does not have Git installed

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/users-formula#115]
Was running this formula on a fresh installation without Git installed.  Got the following error:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 681, in sls
        ret = st_.state.call_high(high_)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'git.config'
```

Installed Git (using `git-formula`) and then all OK.

So suggest that the following needs to be added somewhere:

```
include:
  - git
```

Some issues with this:

1. This is introducing a dependency on `git-formula`
1. Won't be required in all cases, due to `{% if 'gitconfig' in user %}` -- so perhaps best to put under this conditional

Happy to submit a PR if required.

**Comment by gravyboat** [comment]
Hi @myii, currently we don't do cross formula dependencies (as you noted in `1`) to try and avoid that sort of issue. Do you think we need to do the include? I don't but I'm very biased as I've been working with this stuff for a while. I like the idea behind 2, but I just hate to introduce dependencies as that opens the door for all sorts of weird include conditionals.

**Comment by aboe76** [comment]
@myii  Did you have a gitconfig line in your pillar? otherwise the users-formula wouldn't ask for git.config...

see
https://github.com/saltstack-formulas/users-formula/blob/master/users/init.sls#L418-L435

**Comment by gravyboat** [comment]
@aboe76 Yeah he did, that's why this happened. He's talking about workarounds to include the git formula in the event that users DO have a git config line. I'm definitely more of a fan of 'let it error' so people will know they need to include git as opposed to including it, but it's worth discussing.

**Comment by aboe76** [comment]
@gravyboat yes, I agree on what you are saying then the fault lies in the state git part that's isn't producing the correct warning message but an error.

**Comment by gravyboat** [comment]
Agreed, this should probably be an issue in the main Salt repo now that you mention that. I bet someone already made it in fact.

**Comment by aboe76** [comment]
@gravyboat nope, can't find an issue for state.git...

**Comment by myii** [comment]
@gravyboat @aboe76: Thanks to you both for the prompt responses.

> ... we don't do cross formula dependencies (as you noted in 1) to try and avoid that sort of issue. Do you think we need to do the include? I don't but I'm very biased as I've been working with this stuff for a while.

Definitely agree to avoid these dependencies.

> I like the idea behind 2, but I just hate to introduce dependencies as that opens the door for all sorts of weird include conditionals.

Is there a way to simply check if Git is installed?  I've had a browse around the documentation and the closest I could seem to get to this was checking with `pkg.version`.  But then I ran into the bug mentioned at https://github.com/saltstack/salt/issues/28589.  Other than a hacky `cmd.run`, is there a better way that I'm overlooking?

> Did you have a gitconfig line in your pillar?

Yes, I've been using the same pillar for numerous minions but this is the first time that I ran this formula without Git installed beforehand.

> So this should be bug in state.git.

> Agreed, this should probably be an issue in the main Salt repo now that you mention that.

> nope, can't find an issue for state.git...

I can go ahead and do that.  Other than linking back to this issue, is there any further information that should be provided?

---

In the meantime, as I've mentioned above, a check for Git would be more than sufficient.  Besides that, updating `pillar.example` with a comment for the `gitconfig` section would be helpful.  Borrowing from @aboe76 above, something like:

```
    # Using gitconfig without Git installed will result in an error
    # https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html:
    # This state module now requires git 1.6.5 (released 10 October 2009) or newer.
    gitconfig:
      user.name: B User
      user.email: buser@example.com
      url."https://".insteadOf: "git://"
```
