### ISSUE TITLE
sudo state does not handle usernames containing periods

### ISSUE THREAD

**Issue by vschumaker** [saltstack-formulas/users-formula#118]
From the sudoers manpage.

> The #includedir directive can be used to create a sudo.d directory that the system package manager can drop sudoers rules into as part of package installation. For example, given:
> # includedir /etc/sudoers.d
> 
> sudo will read each file in /etc/sudoers.d, skipping file names that end in '~' or contain a '.' character to avoid causing problems with package manager or editor temporary/backup files.

As a workaround, this formula should replace periods with underscores where appropriate.

**Comment by ashokrajar** [comment]
Any plans to merge this. I hope this is a common use case where username contains a period.

**Comment by aboe76** [comment]
@ashokrajar why replace periods with underscores, only in sudoers, won't this cause issues,
with creating an user with a period in it's name that has sudoers true, and can't use sudo, because the usersname doesn't match...

Isn't it better to have the formula error on a user with a period in it's name with a description that sudoers shouldn't use periods....

**Comment by ashokrajar** [comment]
Filename under

**Comment by ashokrajar** [comment]
We are not changing the username inside the sudoer config. This will only change the filename under /etc/sudoers.d.

Filename under /etc/sudoers.d doesn't support periods. So we are creating files replacing periods with underscore and keeping the username unchanged.

**Comment by ashokrajar** [comment]
Many organizations uses their email to be repurposed as system username to keep things simple and organized. So restricting salt users not to have period in their username may stop them from using this formula and create their own or even find reasons not to use salt stack itself or IMO it's duplicate effort.

**Comment by aboe76** [comment]
@ashokrajar thanks for explaining it.
