### ISSUE TITLE
ssh_auth.absent doesn't work if createHome is False

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack-formulas/users-formula#164]
In ssh_auth.absent there is a require for "file: users_{{ name }}_user", but this resource is not created if createHome is False. This can happen (as it's my case) when the home directory is maintained by another tool and has to be ignored by Saltstack.

Is there another way of using ssh_auth.absent without having to use createHome?

**Comment by 0xf10e** [comment]
Hmmm… there shouldn't be any conditionals  necessary for this when `createHome` is `False` as an user may not have a `~/.ssh` (or even home-) directory where an `authorized_keys` could be found in.

**Comment by rsuarezsoto** [comment]
I'm sorry, but I think I don't understand. Do you mean that this is a bug because it shouldn't happen, or that it is a "feature" because there needs to be a home directory for `~/.ssh`?

**Comment by 0xf10e** [comment]
Actually there doesn't need to be a home directory to have SSH-keys. It's just the default of `~/.ssh/authorized_keys` residing in the user's home directory (see [`AuthorizedKeysFile`](http://man.openbsd.org/sshd_config#AuthorizedKeysFile)).
So there shouldn't be a dependency on the existence of the user's home directory, only a check if the user's `AuthorizedKeysFile` (which might be somewhere else anyway) exists.

**Comment by noelmcloughlin** [comment]
Addressed in #192
