### ISSUE TITLE
vimrc state does not work

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/users-formula#166]
The `vimrc` state fails.

**vimrc.sls**
```
include:
  - users
  - vim

```

**ERROR**
```
    Specified SLS vim in saltenv base is not available on the salt master or through a configured fileserver
```

**Comment by EvaSDK** [comment]
The readme says it depends on the vim-formula being present in your installation. Did you install it ?

**Comment by noelmcloughlin** [comment]
No @EvaSDK I missed that sentence.  I'll test next week.  Thanks!!

**Comment by noelmcloughlin** [comment]
#177
