### ISSUE TITLE
On RedHat RHEL7  deployed users don't have a copy of /etc/skel

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/users-formula#190]
When using the users formula on a RHEL7 the created users in a different folder than /home don't have a copy of the /etc/skel files in their home at creation (no .bash_profile for example). 

Does someone have an idea on where this bug might come from ? Should I file upstream on the user.present state ? 

```
# useradd skel_test_arthur --home-dir /srv/adm/users/skel_test_arthur
#  ls -alh /srv/adm/users/skel_test_arthur/
total 16K
drwx------.  2 skel_test_arthur skel_test_arthur   62 20 nov.  12:41 .
drwxr-xr-x. 57 root             root             4,0K 20 nov.  12:41 ..
-rw-r--r--.  1 skel_test_arthur skel_test_arthur   18 22 mai   15:50 .bash_logout
-rw-r--r--.  1 skel_test_arthur skel_test_arthur  193 22 mai   15:50 .bash_profile
-rw-r--r--.  1 skel_test_arthur skel_test_arthur  231 22 mai   15:50 .bashrc
```
works so I guess selinux (which can sometimes interfere) seems out of the equation.

**Comment by noelmcloughlin** [comment]
This issue should be fixed by https://github.com/saltstack-formulas/users-formula/pull/183
