### ISSUE TITLE
[BUG] vimrc state keeps not working

### ISSUE THREAD

**Issue by fzipi** [saltstack-formulas/users-formula#213]
### Formula commit hash / release tag

Using 9ee7636477e20ad6597da2dd41375e858f644e4d.

### Versions reports (master & minion)

I'm just using `kitchen test default-ubuntu-1804-2019-2-py3`

### Pillar / config used

Testing the pillar with the example test (`test/salt/pillar/default.sls`), and small patch. See below.

---

### Describe the bug

After reading #166 , we still cannot make this state to work.
I'm getting always
```
       salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'use_vim_formula'
       [CRITICAL] Rendering SLS 'base:users.vimrc' failed: Jinja variable 'dict object' has no attribute 'use_vim_formula'
       [DEBUG   ] LazyLoaded highstate.output
       local:
           Data failed to compile:
       ----------
           Rendering SLS 'base:users.vimrc' failed: Jinja variable 'dict object' has no attribute 'use_vim_formula'
```
### Steps to reproduce the bug

I'm using this patch in master to test:
```
diff --git a/kitchen.yml b/kitchen.yml
index 69d8b54..4b72387 100644
--- a/kitchen.yml
+++ b/kitchen.yml
@@ -180,6 +180,10 @@ provisioner:
   salt_install: none
   require_chef: false
   formula: users
+  dependencies:
+  - name: vim
+    repo: git
+    source: https://github.com/saltstack-formulas/vim-formula.git
   salt_copy_filter:
     - .kitchen
     - .git
@@ -198,12 +202,23 @@ suites:
       state_top:
         base:
           '*':
+            - vim
             - users
+            - users.vimrc
       pillars:
         top.sls:
           base:
             '*':
+              - vim
               - users
+        vim.sls:
+          vim:
+            managed_vimrc: true
+            allow_localrc: false
+            config:
+              syntax: 'on'
+              colors: desert
+
       pillars_from_files:
         users.sls: test/salt/pillar/default.sls
     verifier:
diff --git a/test/integration/default/controls/config_spec.rb b/test/integration/default/controls/config_spec.rb
index 6af3cf9..0f28157 100644
--- a/test/integration/default/controls/config_spec.rb
+++ b/test/integration/default/controls/config_spec.rb
@@ -10,3 +10,13 @@ control 'users configuration' do
     its('mode') { should cmp '0750' }
   end
 end
+
+control 'vim formula works' do
+  title 'formula should createfile'
+
+  describe file('/home/auser/.vimrc') do
+    it { should be_owned_by 'auser' }
+    its('mode') { should cmp '0644' }
+    its('content') { should match /syntax on/ }
+  end
+end
diff --git a/test/salt/pillar/default.sls b/test/salt/pillar/default.sls
index 0bf7025..23da8d8 100644
--- a/test/salt/pillar/default.sls
+++ b/test/salt/pillar/default.sls
@@ -33,6 +33,7 @@ users:
   ## Minimal required pillar values
   auser:
     fullname: A User
+    manage_vimrc: true
 
   ## Full list of pillar values
   buser:
```

### Expected behaviour

A `/home/auser/.vimrc` file should exist.

### Attempts to fix the bug
Well, many. There seems to be a difference between documentation in docs/README.rst:
`This depends on the vim-formula being available and pillar \`users:use_vim_formula: True\`.` vs. using `users-formula: use_vim_formula: true`.

If I remove/change `{% if users.use_vim_formula %}` in `users/vimrc.sls`, of course this error is not there anymore. But then, it never gets executed also.

**Comment by myii** [comment]
@fzipi Thanks for the report, just some initial feedback for you.  While we can look into why `users.vimrc` isn't working, you may find [`users.user_files`](https://github.com/saltstack-formulas/users-formula#users-user-files) more useful overall.  You can use it to manage `.vimrc` and any other files as well.  This is the relevant section in `pillar.example`:

https://github.com/saltstack-formulas/users-formula/blob/1d9a5ef5be4bf0c66d6471effa32a2953637b031/pillar.example#L170-L186

**Comment by fzipi** [comment]
I saw that, seems good. Just trying to be compatible with our old pillars (we were using an ancient users-formula version).

Do you think the `user_files` is going to be the way to do it in the future? (makes sense if you want to be independent of the vim formula)

**Comment by myii** [comment]
@fzipi I would say that `user_files` is a better solution all round, compared to `users.vimrc` specifically.  In the meantime, I didn't see this in your original report:

https://github.com/saltstack-formulas/users-formula/blob/1d9a5ef5be4bf0c66d6471effa32a2953637b031/pillar.example#L4-L5

Note, this is using the `users-formula` pillar key as opposed to `users`.  Do you have that defined somewhere in your setup?

**Comment by fzipi** [comment]
@myii Well, it is your setup. It is using the kitchen test files :)

**Comment by myii** [comment]
@fzipi Well, we're not not currently testing the `users.vimrc` at the current time!

https://github.com/saltstack-formulas/users-formula/blob/1d9a5ef5be4bf0c66d6471effa32a2953637b031/kitchen.yml#L179-L182

This is something that would be worth adding, though.

**Comment by fzipi** [comment]
@myii That's what kind of added with my patch. To test that it is not working, sadly.

**Comment by myii** [comment]
@fzipi I'm having a little look at this, I'll get back to you soon with some feedback.  I see the contradiction that was introduced in #177, as you linked above.

**Comment by myii** [comment]
@fzipi OK, progress made, got the state running but failing:

* https://travis-ci.org/myii/users-formula/jobs/605177029#L3509-L3513

The changes made so far (ignore `.travis.yml`, that's just to prevent all of the instances from running):

* https://github.com/myii/users-formula/commit/354ad389c9f6209c9df9bb5ba4f166156c87b729

**Comment by fzipi** [comment]
Ok, this quick patch makes sense, and it is more or less what I've done:
```
{% if salt['pillar.get']('users-formula:use_vim_formula', False) %}
```

**Comment by myii** [comment]
@fzipi It's working now:

* https://travis-ci.org/myii/users-formula/jobs/605181220#L3345-L3361

Using no `template`:

* https://github.com/myii/users-formula/commit/0654886fb8688854e91147141d35f77ca8171db2

**Comment by fzipi** [comment]
Ok, now the question is `is it really working?` I mean, I've added some tests to see if the file `~/.vimrc` is created. Is that what this state is supposed to do?

**Comment by fzipi** [comment]
Oh, yes. I see it now in my local test :)

**Comment by myii** [comment]
@fzipi You're welcome, thanks for the detailed bug report in the first place.  It makes it much easier to conduct the bug hunt.

Moving forward, the obvious thing is to add these changes to the formula.  There is a breaking change that needs to be avoided if possible, though: there may be users out there who are using `.vimrc` Jinja templates.  So may need to include the option of selecting the template as well, although I'm not keen on that either.

**Comment by fzipi** [comment]
@myii For me the question is in this case if this was woking at all.... I don't see how after introducing the `users.use_vim_formula` could have worked properly...

**Comment by myii** [comment]
@fzipi That most likely happened during the review of #177, specifically:

* https://github.com/saltstack-formulas/users-formula/pull/177#issuecomment-397255426

So [this line](https://github.com/saltstack-formulas/users-formula/pull/177/files#diff-e55ae51ab553f9f41ebd3a89952d4581R3) also needed to be changed after the review but got overlooked.

**Comment by fzipi** [comment]
Maybe relying on the extension? Like if file ends in `.jinja` then apply jinja templating or nothing if not.

**Comment by myii** [comment]
That won't work as-is, since the `source` has been configured to look for `vimrc` without an extension:

https://github.com/saltstack-formulas/users-formula/blob/1d9a5ef5be4bf0c66d6471effa32a2953637b031/users/vimrc.sls#L29-L31

So the least harmful solution appears to be to modify `users/files/vimrc/vimrc` to be an actual `jinja` template.

**Comment by fzipi** [comment]
Well, reading the file, we can think about just keeping things like they are now, and removing the `{{{1` from the file, so they don't get parsed as jinja template tags....

**Comment by myii** [comment]
Actually, I've already done this when managing files with `user_files`.  We can simply wrap most/all of the `vimrc` template in `raw` tags:

```jinja
{% raw -%}
...
{%- endraw %}
```

That will solve this problem, without causing a breaking change.  Just going to test that now.

**Comment by fzipi** [comment]
Oh, that sounds like a lovely solution!

**Comment by myii** [comment]
There we are, that's working:

* https://travis-ci.org/myii/users-formula/jobs/605190619

I'll wrap this all into a PR so we can get this out there.  Thanks again for all of the feedback, @fzipi!

**Comment by fzipi** [comment]
Thanks to you!

**Comment by fzipi** [comment]
If you want to add it to the PR, I've added some inspec test in the patch to verify that .vimrc is being created properly.

**Comment by myii** [comment]
@fzipi Sure, I was just about to work on this!  Do you mind putting this into a PR?  We can merge this fix first and then the InSpec tests.

**Comment by fzipi** [comment]
Created https://github.com/saltstack-formulas/users-formula/pull/214.

**Comment by myii** [comment]
@fzipi Thanks, I'll continue the discussion there.
