### ISSUE TITLE
Posibility to include * files per user

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/users-formula#34]
Something along the lines of
>files:
   this/be/a/path:
    - mode: 644
    - source: salt://path/to/source

And it would include it as { home.dir } / { file.path }

**Comment by aboe76** [comment]
@TaiSHiNet doesn't user_files.sls fit this bill?

**Comment by TaiSHiNet** [comment]
It might, considering it was added over a year after my initial ticket :P  I think we could close it

**Comment by aboe76** [comment]
@TaiSHiNet lol that was what I was thinking...:) can you close this one?

**Comment by TaiSHiNet** [comment]
Sure thing, thanks for checking up!
