### ISSUE TITLE
Allow specifying multiple public/private keys per user

### ISSUE THREAD

**Issue by johtso** [saltstack-formulas/users-formula#51]

**Comment by xenophonf** [comment]
Doesn't ssh_keys_pillar provide this functionality?  I'm using this in my Salt master deployment:

https://github.com/irtnog/salt-pillar-example/blob/242f079858fc5ddb6d89508c742f3ce4ff4a9b1d/salt/example/com/init.sls#L25

A recent pull request of mine just got merged (#77) that sets the correct file ownerships and permissions for key pairs deployed in this manner.

**Comment by aboe76** [comment]
see https://github.com/saltstack-formulas/users-formula/pull/133

it's a work in progress.

**Comment by aboe76** [comment]
@johtso #133 is merged can you check it out?

**Comment by rhertzog** [comment]
I believe this issue is no longer relevant, we can define multiple keys nowadays.
